---
abstract: 'Minimalistic data validation'
author:
  - 'minimalist <minimalist@lavabit.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validate-Tiny
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.008
  Test::More: 0
  List::MoreUtils: 0
resources:
  repository: git://github.com/naturalist/Validate--Tiny.git
  bugtracker: https://github.com/naturalist/Validate--Tiny/issues
version: 0.983
